Much cleaner code: avoids passing  around, now infers it from pwd only where it's needed

diff --git a/ruci b/ruci
--- a/ruci
+++ b/ruci
@@ -78,118 +78,117 @@ usage () { REASON="$*"
   exit 1
 }
 
-getIpFromCname () { CNAME="${1:?}"
-  uci -c "$CNAME/$DIR_UCI_CONFIG" get network.lan.ipaddr
+getIpFromUciConfig () { 
+  uci -c "$DIR_UCI_CONFIG" get network.lan.ipaddr
 }
 
-repoIsClean () { CNAME="${1:?}"
-  repoIsEqualToRev "$CNAME" "-1"
+repoIsClean () {
+  repoIsEqualToRev "-1"
 }
 
-repoIsEqualToRev () { CNAME="${1:?}" ; REV="${2:?}"
-  CNAME_OVERLAY_PATH="$(cd -P "$CNAME/$DIR_OVERLAY"; pwd )"
-  STDOUT="$(hg status --rev $REV "$CNAME_OVERLAY_PATH")" ; RETVAL=$?
+repoIsEqualToRev () { REV="${1:?}"
+  STDOUT="$(hg status --rev $REV "$DIR_OVERLAY")" ; RETVAL=$?
   ([ -z "$STDOUT" ] && [ $RETVAL -eq 0 ]) && return 0 || return 1
 }
 
-repoAutocommit () { CNAME="${1:?}"
-  CNAME_OVERLAY_PATH="$(cd -P "$CNAME/$DIR_OVERLAY"; pwd )"
-  hg commit -A -m "Autocommit before pulling from $CNAME." "$CNAME_OVERLAY_PATH"
+repoAutocommit () {
+  hg commit -A -m "Autocommit local changes before pulling." "$DIR_OVERLAY"
 }
 
-repoLastRev () { CNAME="${1:?}"
-  CNAME_OVERLAY_PATH="$(cd -P "$CNAME/$DIR_OVERLAY"; pwd )"
-  hg log --template "{node}\n" -l 1 "$CNAME_OVERLAY_PATH"
+repoLastRev () {
+  hg log --template "{node}\n" -l 1 "$DIR_OVERLAY"
 }
 
-writeLastRevPushed () { CNAME="${1:?}"
-  repoLastRev "$CNAME" > "$CNAME/.lastrevpushed"
+writeLastRevPushed () {
+  repoLastRev > ".lastrevpushed"
 }
 
-readLastRevPushed () { CNAME="${1:?}"
-  [ -s "$CNAME/.lastrevpushed" ] && cat "$CNAME/.lastrevpushed" || echo 0
+readLastRevPushed () {
+  [ -s ".lastrevpushed" ] && cat ".lastrevpushed" || echo 0
 }
 
 tstamp () {
   date +%F_%T.%3N
 }
 
-log () { CNAME="${1:?}" ; shift; TEXT="$*"
+log () { TEXT="$*"
+  [ "$1" == "*" ] && CNAME="*" || CNAME="$(basename `pwd -L`)"
   echo "$TEXT" \
     | sed "/tar: removing leading ... from member/d" \
     | sed "s|^|[$CNAME] $(tstamp): |" \
     | tee -a "$LOGFILE"
 }
  
-try () { CNAME="${1:?}" ; CMDLINE="${2:?}"
+try () { CMDLINE="${1:?}"
   CMD="${CMDLINE%% *}"
+  CNAME="$(basename `pwd -L`)"
   ERRLOG="/tmp/$CMD.${CNAME////}.$EPOCH"
   
   eval "$CMDLINE" &> "$ERRLOG"
   RETVAL=$?
   if [ -r "$ERRLOG" ] && [ -s "$ERRLOG" ] ; then
     sed "s|^|($CMD) |" -i "$ERRLOG"
-    log "$CNAME" "$(<"$ERRLOG")"
+    log "$(<"$ERRLOG")"
   fi
   rm -f "$ERRLOG"
   return $RETVAL
 }
 
-pullConfigFromIp () { CNAME="${1:?}" ; IPADDR="${2:?}" ; SKIP_UPDATE=$3
+pullConfigFromIp () { IPADDR="${1:?}" ; SKIP_UPDATE=$2
   RETVAL=
   
-  if [ -d "$CNAME" ] && [ -z "$SKIP_UPDATE" ] && ! repoIsClean "$CNAME" ; then
-    log "$CNAME" "Directory contains uncommited changes. Autocommiting..."
-    try "$CNAME" "repoAutocommit \"$CNAME\"" \
+  if [ -d "$DIR_OVERLAY" ] && [ -z "$SKIP_UPDATE" ] && ! repoIsClean ; then
+    log "Directory contains uncommited changes. Autocommiting..."
+    try "repoAutocommit" \
       || return
   fi
 
-  mkdir -p "$CNAME/$DIR_PULL_TMP"
+  mkdir -p "$DIR_PULL_TMP"
 
-  log "$CNAME" "Pulling $DIR_OVERLAY from $IPADDR ..."
-  try "$CNAME" "$SSH_PERSIST $IPADDR \"$TAR -c -f - /$DIR_OVERLAY \" >$CNAME/$DIR_PULL_TMP.tar" \
-    || { RETVAL=$? ; rm -rf "$CNAME/$DIR_PULL_TMP"{/,.tar} ; return $RETVAL ; }
+  log "Pulling $DIR_OVERLAY from $IPADDR ..."
+  try "$SSH_PERSIST $IPADDR \"$TAR -c -f - /$DIR_OVERLAY \" >$DIR_PULL_TMP.tar" \
+    || { RETVAL=$? ; rm -rf "$DIR_PULL_TMP"{/,.tar} ; return $RETVAL ; }
   
-  try "$CNAME" "$TAR -x -f $CNAME/$DIR_PULL_TMP.tar -C $CNAME/$DIR_PULL_TMP" \
-    || { RETVAL=$? ; rm -rf "$CNAME/$DIR_PULL_TMP"{/,.tar} ; return $RETVAL ; }
+  try "$TAR -x -f $DIR_PULL_TMP.tar -C $DIR_PULL_TMP" \
+    || { RETVAL=$? ; rm -rf "$DIR_PULL_TMP"{/,.tar} ; return $RETVAL ; }
 
-  rm -rf "$CNAME/$DIR_PULL_TMP/$DIR_OVERLAY/$ETC_FAILSAFE" # Ignore the temp $ETC_FAILSAFE on remote hosts
-  rm -rf "$CNAME/$DIR_PULL_TMP.tar"
+  rm -rf "$DIR_PULL_TMP/$DIR_OVERLAY/$ETC_FAILSAFE" # Ignore the temp $ETC_FAILSAFE on remote hosts
+  rm -rf "$DIR_PULL_TMP.tar"
 
   if [ -z "$SKIP_UPDATE" ] ; then 
-    rm -rf "$CNAME/$DIR_OVERLAY"
-    mv "$CNAME/$DIR_PULL_TMP/$DIR_OVERLAY" "$CNAME/$DIR_OVERLAY"
-    rm -rf "$CNAME/$DIR_PULL_TMP"
+    rm -rf "$DIR_OVERLAY"
+    mv "$DIR_PULL_TMP/$DIR_OVERLAY" "$DIR_OVERLAY"
+    rm -rf "$DIR_PULL_TMP"
   fi
   
-  log "$CNAME" "Pulled successfully."
+  log "Pulled successfully."
 }
 
-pushConfigToIp () { CNAME="${1:?}" ;  IPADDR="${2:?}"
+pushConfigToIp () { IPADDR="${1:?}"
   RETVAL=
   PUSH_FILES=
   
-  try "$CNAME" "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d /etc.failsafe-to-apply/ ]\' "
+  try "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d /etc.failsafe-to-apply/ ]\' "
     RETVAL=$?
     if [ $RETVAL -eq 0 ] ; then
-      log "$CNAME" "Previous push hasn't been confirmed yet. Use \`$CMDNAME confirm $CNAME\` first. Skipping..." 
+      log "Previous push hasn't been confirmed yet. Use \`$CMDNAME confirm [...]\` first. Skipping..." 
       return
     fi
   
-  log "$CNAME" "Sending config with scp to $IPADDR ... "
-  try "$CNAME" "$SSH_PERSIST $IPADDR \"/bin/mkdir -p /tmp/$DIR_PUSH_TMP/\" " \
+  log "Sending config with scp to $IPADDR ... "
+  try "$SSH_PERSIST $IPADDR \"/bin/mkdir -p /tmp/$DIR_PUSH_TMP/\" " \
     || return
   
-  try "$CNAME" "$TAR -c --owner root --group root -f $CNAME/$DIR_PUSH_TMP.tar -C $CNAME/$DIR_OVERLAY/ ./$PUSH_FILELIST" \
-    || { RETVAL=$? ; rm -rf "$CNAME/$DIR_PUSH_TMP"{/,.tar} ; return $RETVAL ; }
+  try "$TAR -c --owner root --group root -f $DIR_PUSH_TMP.tar -C $DIR_OVERLAY/ ./$PUSH_FILELIST" \
+    || { RETVAL=$? ; rm -rf "$DIR_PUSH_TMP.tar" ; return $RETVAL ; }
   
-  try "$CNAME" "$SSH_PERSIST $IPADDR \"$TAR -x -f - -C /tmp/$DIR_PUSH_TMP/ \" <$CNAME/$DIR_PUSH_TMP.tar" \
-    || { RETVAL=$? ; rm -rf "$CNAME/$DIR_PUSH_TMP"{/,.tar} ; return $RETVAL ; }
+  try "$SSH_PERSIST $IPADDR \"$TAR -x -f - -C /tmp/$DIR_PUSH_TMP/ \" <$DIR_PUSH_TMP.tar" \
+    || { RETVAL=$? ; rm -rf "$DIR_PUSH_TMP.tar" ; return $RETVAL ; }
   
-  rm -rf "$CNAME/$DIR_PUSH_TMP.tar"
+  rm -rf "$DIR_PUSH_TMP.tar"
 
-  log "$CNAME" "Config sent. Applying changes..."
-  try "$CNAME" "$SSH_PERSIST $IPADDR \"    /bin/rm -rf /etc.failsafe/ ;
+  log "Config sent. Applying changes..."
+  try "$SSH_PERSIST $IPADDR \"    /bin/rm -rf /etc.failsafe/ ;
                               ( /bin/cp -a /etc /etc.failsafe \
                                 && /bin/rm -rf $PUSH_FILELIST \
                                 && /bin/mv /tmp/$DIR_PUSH_TMP/* / ) \
@@ -197,70 +196,73 @@ pushConfigToIp () { CNAME="${1:?}" ;  IPADDR="${2:?}"
                                 && $REBOOT_CMD & )\" " \
     || return
 
-  writeLastRevPushed "$CNAME"
+  writeLastRevPushed
   
-  log "$CNAME" "Done.$([ $REBOOT_CMD == $NO_REBOOT_CMD ] || echo " Rebooting in $REBOOT_WAIT secs...")"
+  log "Done.$([ $REBOOT_CMD == $NO_REBOOT_CMD ] || echo " Rebooting in $REBOOT_WAIT secs...")"
+
+  CNAME="$(basename `pwd -L`)"
   echo -n " $CNAME" >> "$CNAMES_PUSHED"
 }
 
-confirmConfigToIp () { CNAME="${1:?}" ; IPADDR="${2:?}"
-  log "$CNAME" "Trying to remove $ETC_FAILSAFE in $IPADDR ... "
-  try "$CNAME" "$SSH_PERSIST $IPADDR \"/bin/rm -rfv ${ETC_FAILSAFE:?}\" " \
+confirmConfigToIp () { IPADDR="${1:?}"
+  log "Trying to remove $ETC_FAILSAFE in $IPADDR ... "
+  try "$SSH_PERSIST $IPADDR \"/bin/rm -rfv ${ETC_FAILSAFE:?}\" " \
     || return
 
-  log "$CNAME" "Done."
+  log "Done."
 }
 
-statusConfigFromIp () { CNAME="${1:?}" ; IPADDR="${2:?}"
+statusConfigFromIp () { IPADDR="${1:?}"
   RETVAL=
   STATUSMSG=
-  
-  try "$CNAME" "pullConfigFromIp \"$CNAME\" \"$IPADDR\" skip_update" >/dev/null \
-    || { log "$CNAME" "$IPADDR Down." ; return ; }
 
-  try "$CNAME" "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d $ETC_FAILSAFE ]\' " \
+  CNAME="$(basename `pwd -L`)"
+  
+  try "pullConfigFromIp \"$IPADDR\" skip_update" >/dev/null \
+    || { log "$IPADDR Down." ; return ; }
+
+  try "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d $ETC_FAILSAFE ]\' " \
     && STATUSMSG=" Counting down to revert-to-failsafe..." \
     && echo -n " $CNAME" >> "$CNAMES_PUSHED"
     
   # Compares local working copy with freshly pulled overlay. Returns 0 if they are equal, 1 if differences are found.
-  try "$CNAME" "diff -q . . ; ( cd \"$CNAME\" ; find -L \"$DIR_OVERLAY\" \"$DIR_PULL_TMP/$DIR_OVERLAY\" -type l -printf \"%f\n\"\
+  try "diff -q . . ; ( find -L \"$DIR_OVERLAY\" \"$DIR_PULL_TMP/$DIR_OVERLAY\" -type l -printf \"%f\n\"\
                 | diff -X - -qr \"$DIR_OVERLAY\" \"$DIR_PULL_TMP/$DIR_OVERLAY\" ) " >/dev/null
     RETVAL=$?
 
   # Makes the freshly pulled overlay a working copy, to compare against past revisions.
-  mv "$CNAME/$DIR_OVERLAY" "$CNAME/$DIR_OVERLAY.bkp"
-  mv "$CNAME/$DIR_PULL_TMP/$DIR_OVERLAY" "$CNAME/$DIR_OVERLAY"
-  rm -rf "$CNAME/$DIR_PULL_TMP"
+  mv "$DIR_OVERLAY" "$DIR_OVERLAY.bkp"
+  mv "$DIR_PULL_TMP/$DIR_OVERLAY" "$DIR_OVERLAY"
+  rm -rf "$DIR_PULL_TMP"
   
   case $RETVAL in
     0)      # Local and remote copies are equal, that means we can consider the current revision as pushed
             # even if it wasn't done with "action push". So, update LastRevPushed cookie
             # If you do "hg commit; ruci push; hg rollback; ...; hg commit", then a simple
             # "hg status" should update/fix cookies that point to vanished changeset ids.
-      writeLastRevPushed "$CNAME"
-      log "$CNAME" "$IPADDR Reachable and updated.$STATUSMSG"
+      writeLastRevPushed
+      log "$IPADDR Reachable and updated.$STATUSMSG"
     ;;
     1)      # If copies differ, might be because local has a new revision waiting to be pushed,
             # (in which case working copy is identical to the one in revision readLastRevPushed)
-      if repoIsEqualToRev "$CNAME" "$(readLastRevPushed "$CNAME")" ; then
-        log "$CNAME" "$IPADDR Reachable, outdated. Remote revision $(readLastRevPushed "$CNAME"|cut -b -12).$STATUSMSG"
+      if repoIsEqualToRev "$(readLastRevPushed)" ; then
+        log "$IPADDR Reachable, outdated. Remote revision $(readLastRevPushed|cut -b -12).$STATUSMSG"
       else  # or else because changes happened only remotely.
-        log "$CNAME" "$IPADDR Reachable, with remote untracked changes. Please pull, manually merge and commit.$STATUSMSG"
+        log "$IPADDR Reachable, with remote untracked changes. Please pull, manually merge and commit.$STATUSMSG"
       fi
       echo -n "|$CNAME" >> "$CNAMES_DIRTY"
     ;;
-    *) log "$CNAME" "Unknown error ($RETVAL) in diff.$STATUSMSG" ;;
+    *) log "Unknown error ($RETVAL) in diff.$STATUSMSG" ;;
   esac
   
   # Clean up the comparison scenario and leave everything as it was previously
-  rm -rf "$CNAME/$DIR_OVERLAY"
-  mv "$CNAME/$DIR_OVERLAY.bkp" "$CNAME/$DIR_OVERLAY"
+  rm -rf "$DIR_OVERLAY"
+  mv "$DIR_OVERLAY.bkp" "$DIR_OVERLAY"
 }
 
 pullConfigs () {
   ARG=
   IPADDR=
-  CNAME=
   
   while [ -n "$1" ]; do
     ARG="$1"
@@ -270,16 +272,16 @@ pullConfigs () {
       -i|--ip ) IPADDR="$1" ; shift ;;
       -z|--gzip ) TAR="$TAR -z" ;;
       * )
-        CNAME="$ARG"
-
-        if ! [ -d "$CNAME/$DIR_UCI_CONFIG" ] && [ -z "$IPADDR" ] ; then 
-          log "$CNAME" "UCI config directory not found! Please prepend --ip to specify where to pull from."
-          continue
-        fi
-	
-        [ -z "$IPADDR" ] && IPADDR=$(getIpFromCname "$CNAME")
-  
-        pullConfigFromIp "$CNAME" "$IPADDR" &
+        cd "$ARG"
+          if ! [ -d "$DIR_UCI_CONFIG" ] && [ -z "$IPADDR" ] ; then 
+            log "UCI config directory not found! Please prepend --ip to specify where to pull from."
+            continue
+          fi
+    
+          [ -z "$IPADDR" ] && IPADDR=$(getIpFromUciConfig)
+    
+          pullConfigFromIp "$IPADDR" &
+        cd "$OLDPWD"
         
         unset IPADDR
       ;;
@@ -290,7 +292,6 @@ pullConfigs () {
 pushConfigsSafe () {
   ARG=
   IPADDR=
-  CNAME=
     
   # Parse args and populate targets list
   while [ -n "$1" ]; do
@@ -300,17 +301,17 @@ pushConfigsSafe () {
     case "$ARG" in
       -i|--ip ) IPADDR="$1"; shift ;;
       * )
-        CNAME="$ARG"
-          
-        [ -d "$CNAME/$DIR_UCI_CONFIG" ] \
-          || { log "$CNAME" "UCI config directory not found! All targets must be valid. Aborting..." ; exit 1 ; }
+        cd "$ARG"
+          [ -d "$DIR_UCI_CONFIG" ] \
+            || { log "UCI config directory not found! All targets must be valid. Aborting..." ; exit 1 ; }
 
-        [ -z "$IPADDR" ] && IPADDR=$(getIpFromCname "$CNAME")
-  
-        # Check local repo is clean
-        if ! repoIsClean "$CNAME" ; then
-          log "$CNAME" "Directory contains uncommited changes. Please commit first. Aborting..." ; exit 2
-        fi
+          [ -z "$IPADDR" ] && IPADDR=$(getIpFromUciConfig)
+    
+          # Check local repo is clean
+          if ! repoIsClean ; then
+            log "Directory contains uncommited changes. Please commit first. Aborting..." ; exit 2
+          fi
+        cd "$OLDPWD"
         
         unset IPADDR
       ;;
@@ -321,10 +322,10 @@ pushConfigsSafe () {
         PUSH_FILES=
   
         # Open ssh persistent connection
-        try "$CNAME" "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d $ETC_FAILSAFE ]\' "
+        try "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d $ETC_FAILSAFE ]\' "
           RETVAL=$?
           if [ $RETVAL -eq 0 ] ; then
-            log "$CNAME" "Previous push hasn't been confirmed yet. Use \`$CMDNAME confirm $CNAME\` first. Aborting..." 
+            log "Previous push hasn't been confirmed yet. Use \`$CMDNAME confirm ...\` first. Aborting..." 
             exit 3
           fi
 
@@ -343,17 +344,17 @@ pushConfigsSafe () {
 #####
         
         for file in $PUSH_FILELIST; do
-          PUSH_FILES="$PUSH_FILES $CNAME/$DIR_OVERLAY/$file"
+          PUSH_FILES="$PUSH_FILES $DIR_OVERLAY/$file"
         done
         
-        log "$CNAME" "Sending config with scp to $IPADDR ... "
-        try "$CNAME" "$SSH_PERSIST $IPADDR \"/bin/mkdir -p /tmp/etc.new.$EPOCH\" " \
+        log "Sending config with scp to $IPADDR ... "
+        try "$SSH_PERSIST $IPADDR \"/bin/mkdir -p /tmp/etc.new.$EPOCH\" " \
           || return
-        try "$CNAME" "scp -pr $PUSH_FILES $IPADDR:/tmp/etc.new.$EPOCH/ >/dev/null" \
+        try "scp -pr $PUSH_FILES $IPADDR:/tmp/etc.new.$EPOCH/ >/dev/null" \
           || return
         
-        log "$CNAME" "Config sent. Applying changes..."
-        try "$CNAME" "$SSH_PERSIST $IPADDR \"    /bin/rm -rf $ETC_FAILSAFE ;
+        log "Config sent. Applying changes..."
+        try "$SSH_PERSIST $IPADDR \"    /bin/rm -rf $ETC_FAILSAFE ;
                                     ( /bin/cp -a /etc $ETC_FAILSAFE \
                                       && /bin/rm -rf $PUSH_FILELIST \
                                       && /bin/mv /tmp/etc.new.$EPOCH/* /etc/ ) \
@@ -361,7 +362,7 @@ pushConfigsSafe () {
                                       && $REBOOT_CMD & )\" " \
           || return
 
-        log "$CNAME" "Done.$([ $REBOOT_CMD == $NO_REBOOT_CMD ] || echo " Rebooting in $REBOOT_WAIT secs...")"
+        log "Done.$([ $REBOOT_CMD == $NO_REBOOT_CMD ] || echo " Rebooting in $REBOOT_WAIT secs...")"
         echo -n " $CNAME" >> "$CNAMES_PUSHED"
 
 ####
@@ -370,7 +371,6 @@ pushConfigsSafe () {
 pushConfigs () {
   ARG=
   IPADDR=
-  CNAME=
   
   while [ -n "$1" ]; do
     ARG="$1"
@@ -386,14 +386,14 @@ pushConfigs () {
         fi
       ;;
       * )
-        CNAME="$ARG"
-
-        [ -d "$CNAME/$DIR_UCI_CONFIG" ] \
-          || { log "$CNAME" "UCI config directory not found. Ignoring host." ; unset IPADDR ; continue ; }
-  
-        [ -z "$IPADDR" ] && IPADDR=$(getIpFromCname "$CNAME")
-  
-        pushConfigToIp "$CNAME" "$IPADDR" &
+        cd "$ARG"
+          [ -d "$DIR_UCI_CONFIG" ] \
+            || { log "UCI config directory not found. Ignoring host." ; unset IPADDR ; continue ; }
+    
+          [ -z "$IPADDR" ] && IPADDR=$(getIpFromUciConfig)
+    
+          pushConfigToIp "$IPADDR" &
+        cd "$OLDPWD"
         
         unset IPADDR
       ;;
@@ -402,36 +402,40 @@ pushConfigs () {
 }
 
 confirmConfigs () {
-  CNAME=
+  ARG=
   IPADDR=
   
   while [ -n "$1" ]; do
-    CNAME="$1"
+    ARG="$1"
     shift
   
-    [ -d "$CNAME/$DIR_UCI_CONFIG" ] \
-      || { log "$CNAME" "UCI config directory not found. Ignoring host." ; continue ; }
-    
-    IPADDR=$(getIpFromCname "$CNAME")
+    cd "$ARG"
+      [ -d "$DIR_UCI_CONFIG" ] \
+        || { log "UCI config directory not found. Ignoring host." ; continue ; }
+      
+      IPADDR=$(getIpFromUciConfig)
 
-    confirmConfigToIp "$CNAME" "$IPADDR" &
+      confirmConfigToIp "$IPADDR" &
+    cd "$OLDPWD"
   done
 }
 
 statusConfigs () {
-  CNAME=
+  ARG=
   IPADDR=
   
   while [ -n "$1" ]; do
-    CNAME="$1"
+    ARG="$1"
     shift
 
-    [ -d "$CNAME/$DIR_UCI_CONFIG" ] \
-      || { log "$CNAME" "UCI config directory not found. Ignoring host." ; continue ; }
-    
-    IPADDR=$(getIpFromCname "$CNAME")
-    
-    statusConfigFromIp "$CNAME" "$IPADDR" &
+    cd "$ARG"
+      [ -d "$DIR_UCI_CONFIG" ] \
+        || { log "UCI config directory not found. Ignoring host." ; continue ; }
+      
+      IPADDR=$(getIpFromUciConfig)
+      
+      statusConfigFromIp "$IPADDR" &
+    cd "$OLDPWD"
   done
 }
 
@@ -447,7 +451,11 @@ case "$ACTION" in
     ${ACTION}Configs "$@"
   ;;
   status )
-    ${ACTION}Configs "${@:-./*/}"
+    if [ -z "$*" ] ; then 
+      ${ACTION}Configs *
+    else 
+      ${ACTION}Configs "$@"
+    fi
   ;;
   "" ) usage ;;
   * ) usage "Error: Unknown action \"$ACTION\"" ;;
